### ISSUE TITLE
Path for Windows

### ISSUE THREAD

**Issue by chuckdee68** [swill/Theme-SolarizedSwill#1]
From your screenshot, I assume you're on MacOS.

For windows, the path is as follows:

C:\Users\USER\AppData\Roaming\Sublime Text 3\Packages

Just an FYI.

**Comment by swill** [comment]
Thank you. I will add that to the Readme. :)

**Comment by swill** [comment]
I have added the Windows path.  Can you send me the navigation path to enable the theme on Windows?  I will add it as well so people have complete Window instructions as well.

Thanks for the support.  :)

**Comment by chuckdee68** [comment]
That part is the same, i.e. 

`Sublime Text > Preferences > Color Schemes > Theme-SolarizedSwill > SolarizedSwill`

And thanks for creating this!

**Comment by swill** [comment]
Thanks for confirming.  👍 

Hope you enjoy.  Let me know if you have any suggestions to make it better.  I have mainly covered my use cases and have not really focused on completeness.  

I think we can probably close this issue unless you have more suggestions on this topic.  Thanks again...
